# Generated by Django 3.2.16 on 2022-12-21 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('method_of_preparation', models.TextField()),
                ('time_of_preparation', models.IntegerField()),
                ('serves', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('recipe_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
