# Generated by Django 3.2.16 on 2022-12-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
